export default Object.freeze({
  WELCOME: 'WelcomeScreen',
  LOGIN: 'LoginScreen',
  REGISTER: 'RegisterScreen',
  STARTER: 'StarterScreen',
  LIST_ASSOCIATION: 'ListAssociationScreen',
  NEW_ASSOCIATION: 'NewAssociationScreen',
  ASSOCIATION_DETAIL: 'AssociationDetailScreen',
  USER_COMPTE: 'CompteScreen',
  TRANSACTION: 'TransactionNavigator',
  RECHARGE: 'RechargeScreen',
  RETRAIT: 'RetraitScreen',
  PROFILE: 'ProfileScreen',
  PARAM: 'ConnexionParamScreen',
});
