export default Object.freeze({
  WELCOME: 'WelcomeScreen',
  LOGIN: 'LoginScreen',
  REGISTER: 'RegisterScreen',
  STARTER: 'StarterScreen',
  LIST_ASSOCIATION: 'ListAssociationScreen',
  NEW_ASSOCIATION: 'NewAssociationScreen',
  ASSOCIATION_DETAIL: 'AssociationDetailScreen',
  USER_COMPTE: 'CompteScreen',
  TRANSACTION: 'TransactionNavigator',
  RECHARGE: 'RechargeScreen',
  RETRAIT: 'RetraitScreen',
  PROFILE: 'ProfileScreen',
  PARAM: 'ConnexionParamScreen',
  NEW_TRANSACTION: 'NewTransactionScreen',
  TRANSACTION_HOME: 'TransactionScreen',
  ASSOCIATION_TAB: 'AssociationTabNavigator',
  CAISSE: 'CaisseScreen',
  COTISATION: 'CotisationScreen',
  MEMBER: 'MemberScreen',
  ENGAGEMENT: 'EngagementScreen',
  MEMBER_COMPTE: 'MemberCompteScreen',
  DASHBOARD: 'DashboardNavigator',
});
